#!/usr/bin/env python3
"""Generate `crates/bui-text/src/bitmap_data.rs` from a TrueType font.

Renders printable ASCII (0x20..=0x7E) at a fixed pixel size into a
grayscale (0..255) alpha mask per glyph. The runtime emits one
alpha-tinted rect per non-zero pixel — antialiased edges look
notably smoother than the previous 1-bit threshold.

The default source is macOS's bundled SF Mono. Replace with DejaVu Sans
Mono (or any CC0/OFL monospace TTF) before redistributing.

Usage:
    python3 tools/gen_bitmap_font.py [font_path] [size]
"""

import sys
from PIL import Image, ImageFont, ImageDraw

DEFAULT_FONT = '/System/Library/Fonts/SFNSMono.ttf'
DEFAULT_SIZE = 16
CELL_W = 11
CELL_H = 20
ORIGIN_X = 1
ORIGIN_Y = -2
BASELINE = 14  # row of the typographic baseline within the cell


def main() -> None:
    font_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    size = int(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_SIZE
    font = ImageFont.truetype(font_path, size)

    print("// Auto-generated by tools/gen_bitmap_font.py.")
    print(f"// Source: {font_path} at size {size}.")
    print(f"// Cell: {CELL_W} columns x {CELL_H} rows. One u8 per pixel,")
    print(f"// row-major, holding the antialiased alpha (0..255).")
    print(f"// Baseline at row {BASELINE}.")
    print("//")
    print("// To regenerate (or swap to a CC0 font):")
    print("//     python3 tools/gen_bitmap_font.py [font_path] [size]")
    print()
    print(f"pub const CELL_W: usize = {CELL_W};")
    print(f"pub const CELL_H: usize = {CELL_H};")
    print(f"pub const BASELINE: usize = {BASELINE};")
    print(f"pub const FIRST_CODEPOINT: u32 = 0x20;")
    print(f"pub const LAST_CODEPOINT: u32 = 0x7E;")
    print()
    print(
        f"pub const GLYPHS: [[u8; {CELL_W * CELL_H}]; {0x7F - 0x20}] = ["
    )

    for cp in range(0x20, 0x7F):
        img = Image.new('L', (CELL_W + 4, CELL_H + 4), 0)
        ImageDraw.Draw(img).text((ORIGIN_X, ORIGIN_Y), chr(cp), font=font, fill=255)
        pixels = []
        for y in range(CELL_H):
            for x in range(CELL_W):
                pixels.append(img.getpixel((x, y)))
        char_repr = repr(chr(cp))
        # Pretty-print: one row per source line, alpha as 3-digit hex.
        rows = []
        for y in range(CELL_H):
            row = ', '.join(
                f"0x{pixels[y * CELL_W + x]:02x}" for x in range(CELL_W)
            )
            rows.append(row)
        print(f"    [")
        for r in rows:
            print(f"        {r},")
        print(f"    ], // {char_repr}")
    print("];")


if __name__ == '__main__':
    main()
